on: [push]

name: Daas Automated Testing

env:
  webappname: daasdevops$RANDOM

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login to Azure
      uses: azure/login@v1
      continue-on-error: false
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: false
    
    - name: Creating App Service Plan
      run: |
        az appservice plan create --name $webappname --resource-group DAAS-DevOps-Testing --sku B1
    
    - name: Creating Web App
      run: |
        az webapp create --name $webappname --resource-group DAAS-DevOps-Testing --plan $webappname
        az webapp config set --resource-group DAAS-DevOps-Testing --name $webappname --always-on true
        echo Adding MSBuild App Setting
        az webapp config appsettings set --resource-group DAAS-DevOps-Testing --name $webappname --settings MSBUILD_PATH=%MSBUILD_15_DIR%\\msbuild.exe
    
    - name: Setting up Github
      run: |
        az webapp deployment source config --name $webappname --resource-group DAAS-DevOps-Testing \
                --repo-url $gitrepo --branch master --manual-integration
