on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login to Azure
      uses: azure/login@v1
      continue-on-error: false
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: false
    
    - run: |
        gitrepo=https://github.com/puneetg1983/WebCampGit
        webappname=daasdevopsdemowebcamp$RANDOM
        az appservice plan create --name $webappname --resource-group DAAS-DevOps-Testing --sku B1
        az webapp create --name $webappname --resource-group DAAS-DevOps-Testing --plan $webappname
        az webapp config set --resource-group DAAS-DevOps-Testing --name $webappname --always-on true
        az webapp config appsettings set --resource-group DAAS-DevOps-Testing --name $webappname --settings MSBUILD_PATH=%MSBUILD_15_DIR%\msbuild.exe
        az webapp deployment source config --name $webappname --resource-group DAAS-DevOps-Testing \
        --repo-url $gitrepo --branch master --manual-integration
