on: [push]

name: Daas Automated Testing

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      GitRepoAspNet: https://github.com/puneetg1983/WebCampGit
    
    steps:
    
    - name: Generate Unique Site Name
      run: echo SiteName=daasdevops$(date +%s) >> $GITHUB_ENV
    
    - name: Login to Azure
      uses: azure/login@v1
      continue-on-error: false
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    - name: Clearing existing Resources in Resource Group
      run: |
        $resources = az resource list --resource-group myResourceGroup | ConvertFrom-Json
        Write-Host "Deleting Web Apps"
        foreach ($resource in $resources) {
            if ($resource.id -like 'providers/Microsoft.Web/sites/') {
              az resource delete --resource-group myResourceGroup --ids $resource.id --verbose
            }
        }
        
        Write-Host "Deleting App Service Plans"
        foreach ($resource in $resources) {
            if ($resource.id -like 'providers/Microsoft.Web/serverfarms/') {
              az resource delete --resource-group myResourceGroup --ids $resource.id --verbose
            }
        }

    - name: Creating App Service Plan
      run: |
        az appservice plan create --name ${{ env.SiteName }} --resource-group DAAS-DevOps-Testing --sku B1
    
    - name: Creating Web App
      run: |
        az webapp create --name ${{ env.SiteName }} --resource-group DAAS-DevOps-Testing --plan ${{ env.SiteName }}
        az webapp config set --resource-group DAAS-DevOps-Testing --name ${{ env.SiteName }} --always-on true
        echo Adding MSBuild App Setting
        az webapp config appsettings set --resource-group DAAS-DevOps-Testing --name ${{ env.SiteName }} --settings MSBUILD_PATH=%MSBUILD_15_DIR%\\msbuild.exe
    
    - name: Setting up Github
      run: |
        az webapp deployment source config --name ${{ env.SiteName }} --resource-group DAAS-DevOps-Testing \
                --repo-url ${{ env.GitRepoAspNet }} --branch master --manual-integration
